# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{negval-deadlock_retry}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamis Buck", "Mike Perham", "Denis Sukhonin"]
  s.date = %q{2011-02-15}
  s.description = %q{Provides automatical deadlock retry and logging functionality for ActiveRecord and MySQL}
  s.email = %q{d.sukhonin@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "README",
    "Rakefile",
    "lib/deadlock_retry.rb",
    "test/deadlock_retry_test.rb"
  ]
  s.homepage = %q{http://github.com/neglectedvalue/deadlock_retry}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Provides automatical deadlock retry and logging functionality for ActiveRecord and MySQL}
  s.test_files = [
    "test/deadlock_retry_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

